#!/usr/bin/perl

use Getopt::Long;

# $opt_err = 0;
# $opt_out = 0;

# GetOptions('err' => \$opt_err, 'out' => \$opt_out);

my $hoge = int(rand(10000));

my $stdout;
my $stderr;
foreach my $line (<>) {
    my $str = $line;
    if ($str =~ m/^(# @\$-o)/) {
	$str =~s/# @\$-o //;
	$stdout = $str;
    } elsif ($str =~ m/^(# @\$-e)/) {
	$str =~s/# @\$-e //;
	$stderr = $str;
    } elsif ($str =~ m/^(# )/) {
    } else {
	$file = 'foo' . $hoge;
	open ( SH , ">> $file" );
	    print SH "$str\n";
	close ( SH );
    }
}

system("/bin/bash $file 1> $stdout 2>$stderr");
unlink $file;
