#!/usr/bin/perl
package xcrypt;

use File::Copy;

my $savefile = "xcrypt_save.pl";

if ($ENV{PATH} eq '') {
    $ENV{PATH} = $ENV{XCRYPT};
} else {
    $ENV{PATH} = $ENV{XCRYPT} . ':' . $ENV{PATH};
}

if ($ENV{PERL5LIB} eq '') {
    $ENV{PERL5LIB} = $ENV{XCRYPT};
} else {
    $ENV{PERL5LIB} = $ENV{XCRYPT} . ":" . $ENV{PERL5LIB};
}

unless (-e $savefile) {

rename $ARGV[0] , $savefile;

open ( TMP , "> $ARGV[0]");
print TMP 'package user;' . "\n";
print TMP 'use UI;' . "\n";
print TMP 'use threads;' . "\n";
print TMP 'use threads::shared;' . "\n";
print TMP 'use jobsched;' . "\n";
print TMP 'use base qw(constructor);' . "\n";
open ( USER , "< $savefile") . "\n";
foreach (<USER>) { print TMP "$_"; }
close ( USER );
print TMP 'sub start {my $self = shift;$self->SUPER::start();return $self;}' . "\n";
print TMP 'sub before {my $self = shift;$self->SUPER::before();eval ($self->{before});}' . "\n";
print TMP 'sub after {my $self = shift;$self->SUPER::after();eval ($self->{after});}' . "\n";
print TMP '$jobsched::watch_thread->detach;' . "\n";
close ( TMP );

chmod 0755, $ARGV[0];
system("perl $ARGV[0]");
unlink $ARGV[0];
rename $savefile , $ARGV[0];

} else { print "remove or rename $savefile.\n"; }
