#!/usr/bin/perl

package xcrypt;

use File::Copy;

rename $ARGV[0] , "tmp.pl";

open ( TMP , "> $ARGV[0]");
print TMP '#!/usr/bin/perl' . "\n";
print TMP 'package user;' . "\n";
print TMP 'use Getopt::Long;' . "\n";
print TMP 'use UI;' . "\n";
print TMP 'use threads;' . "\n";
print TMP 'use threads::shared;' . "\n";
print TMP 'use limit;' . "\n";
print TMP 'use jobsched;' . "\n";
print TMP 'use base qw(constructor);' . "\n";
#print TMP 'our $async_thrd;' . "\n";
#print TMP 'our $async_thrd_card : shared = 0;' . "\n";
print TMP '$opt_dry = 0;' . "\n";
print TMP 'GetOptions(\'dry\' => $opt_dry);' . "\n";
open ( USER , "< tmp.pl") . "\n";
foreach (<USER>) {
    print TMP "$_";
}
close ( USER );
print TMP '$jobsched::inventory_watch_thread->detach;' . "\n";
close ( TMP );

chmod 0755, $ARGV[0];

system("$ARGV[0]");

unlink $ARGV[0];
rename "tmp.pl", $ARGV[0];
