#!/usr/bin/perl
package xcrypt;

use File::Copy;

sub get_base_name {
    my $file_name = shift;
    my $basename = $file_name;
    $basename =~ s/(.*)\..*?$/$1/;
    if ($basename eq '') {
        $basename = $file_name;
    }
    return $basename;
}

my $plfile = &get_base_name($ARGV[0]) . '.pl';

if ($ENV{PATH} eq '') {
    $ENV{PATH} = $ENV{XCRYPT};
} else {
    $ENV{PATH} = $ENV{XCRYPT} . ':' . $ENV{PATH};
}

if ($ENV{PERL5LIB} eq '') {
    $ENV{PERL5LIB} = $ENV{XCRYPT};
} else {
    $ENV{PERL5LIB} = $ENV{XCRYPT} . ":" . $ENV{PERL5LIB};
}

unless (-e $plfile) {

#rename $ARGV[0] , $plfile;

open ( TMP , "> $plfile");
print TMP 'package user;' . "\n";
print TMP 'use UI;' . "\n";
print TMP 'use threads;' . "\n";
print TMP 'use threads::shared;' . "\n";
print TMP 'use jobsched;' . "\n";
print TMP 'use base qw(constructor);' . "\n";
print TMP '$separation_symbol = \'!\';' . "\n";
open ( USER , "< $ARGV[0]") . "\n";
foreach (<USER>) { print TMP "$_"; }
close ( USER );
print TMP 'sub start {my $self = shift;$self->SUPER::start();return $self;}' . "\n";
print TMP 'sub before {my $self = shift;$self->SUPER::before();eval ($self->{before});}' . "\n";
print TMP 'sub after {my $self = shift;$self->SUPER::after();eval ($self->{after});}' . "\n";
print TMP '$jobsched::watch_thread->detach;' . "\n";
close ( TMP );

chmod 0755, $plfile;
system("perl $plfile");
unlink $plfile;

} else { die "Can't make $plfile since it has already existed.\n"; }
